"""add invites table

Revision ID: 49fde4947022
Revises: 99d39bfd5bc1
Create Date: 2026-05-09 22:45:36.624060

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49fde4947022"
down_revision: str | Sequence[str] | None = "99d39bfd5bc1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invites",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("invited_by_id", sa.Uuid(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["accepted_by_id"], ["users.id"], name=op.f("fk_invites_accepted_by_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_invites_company_id_companies")),
        sa.ForeignKeyConstraint(
            ["invited_by_id"], ["users.id"], name=op.f("fk_invites_invited_by_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name=op.f("fk_invites_role_id_roles"), ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invites")),
    )
    op.create_index(op.f("ix_invites_company_id"), "invites", ["company_id"], unique=False)
    op.create_index(op.f("ix_invites_role_id"), "invites", ["role_id"], unique=False)
    op.create_index(op.f("ix_invites_token"), "invites", ["token"], unique=True)
    op.create_index(
        "uq_invites_company_id_email_pending",
        "invites",
        ["company_id", "email"],
        unique=True,
        postgresql_where=sa.text("accepted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_invites_company_id_email_pending", table_name="invites", postgresql_where=sa.text("accepted_at IS NULL")
    )
    op.drop_index(op.f("ix_invites_token"), table_name="invites")
    op.drop_index(op.f("ix_invites_role_id"), table_name="invites")
    op.drop_index(op.f("ix_invites_company_id"), table_name="invites")
    op.drop_table("invites")
    # ### end Alembic commands ###
