"""imported orders + nullable order client price

Revision ID: 52d3c18cd680
Revises: 8e95aa4674a9
Create Date: 2026-06-01 21:25:36.358558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '52d3c18cd680'
down_revision: Union[str, Sequence[str], None] = '8e95aa4674a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imported_orders',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('marketplace', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('store_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('platform_order_id', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('upseller_order_no', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('ad_title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('variation_text', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('tracking_code', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('shipping_label_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('invoice_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_imported_orders_company_id_companies')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_imported_orders_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imported_orders')),
    sa.UniqueConstraint('company_id', 'marketplace', 'platform_order_id', 'sku', name='uq_imported_orders_marketplace_platform_order_id_sku'),
    sa.UniqueConstraint('company_id', 'order_id', name='uq_imported_orders_company_id_order_id')
    )
    op.create_index(op.f('ix_imported_orders_company_id'), 'imported_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_imported_orders_order_id'), 'imported_orders', ['order_id'], unique=False)
    op.alter_column('orders', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('orders', 'sale_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_index(op.f('uq_orders_company_id_ad_id_external_order_id'), table_name='orders', postgresql_where='(external_order_id IS NOT NULL)')
    op.create_index('uq_orders_company_id_ad_id_variation_id_external_order_id', 'orders', ['company_id', 'ad_id', 'variation_id', 'external_order_id'], unique=True, postgresql_where=sa.text('external_order_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_orders_company_id_ad_id_variation_id_external_order_id', table_name='orders', postgresql_where=sa.text('external_order_id IS NOT NULL'))
    op.create_index(op.f('uq_orders_company_id_ad_id_external_order_id'), 'orders', ['company_id', 'ad_id', 'external_order_id'], unique=True, postgresql_where='(external_order_id IS NOT NULL)')
    op.alter_column('orders', 'sale_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('orders', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_imported_orders_order_id'), table_name='imported_orders')
    op.drop_index(op.f('ix_imported_orders_company_id'), table_name='imported_orders')
    op.drop_table('imported_orders')
    # ### end Alembic commands ###
