"""'add montador fields'

Revision ID: 7e2e990f490b
Revises: c57941a33511
Create Date: 2026-06-04 20:46:38.582046

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e2e990f490b"
down_revision: str | Sequence[str] | None = "c57941a33511"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies", sa.Column("montador_user_email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True)
    )
    op.add_column(
        "print_designs", sa.Column("image_url_front", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True)
    )
    op.add_column(
        "print_designs", sa.Column("image_url_back", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True)
    )
    op.add_column("print_designs", sa.Column("width_cm", sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column("print_designs", sa.Column("height_cm", sa.Numeric(precision=6, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("print_designs", "height_cm")
    op.drop_column("print_designs", "width_cm")
    op.drop_column("print_designs", "image_url_back")
    op.drop_column("print_designs", "image_url_front")
    op.drop_column("companies", "montador_user_email")
    # ### end Alembic commands ###
