"""add login_attempts

Revision ID: 8e95aa4674a9
Revises: a1b2c3d4e5f6
Create Date: 2026-06-01 19:32:48.289248

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e95aa4674a9"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("firebase_uid", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("email_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "outcome",
            postgresql.ENUM("success", "not_invited", "unverified_email", "missing_uid", name="login_outcome"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("detail", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempts")),
    )
    op.create_index(op.f("ix_login_attempts_email"), "login_attempts", ["email"], unique=False)
    op.create_index("ix_login_attempts_email_created_at", "login_attempts", ["email", "created_at"], unique=False)
    op.create_index("ix_login_attempts_outcome_created_at", "login_attempts", ["outcome", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("ix_login_attempts_outcome_created_at", table_name="login_attempts")
    op.drop_index("ix_login_attempts_email_created_at", table_name="login_attempts")
    op.drop_index(op.f("ix_login_attempts_email"), table_name="login_attempts")
    op.drop_table("login_attempts")
    # Drop the enum type too, so a re-upgrade can recreate it cleanly.
    postgresql.ENUM(name="login_outcome").drop(op.get_bind(), checkfirst=True)
