"""'make print optional on products'

Revision ID: 99d39bfd5bc1
Revises: f8b1292f47b0
Create Date: 2026-05-08 20:17:10.953795

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99d39bfd5bc1"
down_revision: str | Sequence[str] | None = "f8b1292f47b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "print_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("uq_products_spec_id_print_id"), "products", type_="unique")
    op.create_unique_constraint(
        "uq_products_spec_id_print_id",
        "products",
        ["company_id", "spec_id", "print_id"],
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_products_spec_id_print_id", "products", type_="unique")
    op.create_unique_constraint(
        op.f("uq_products_spec_id_print_id"),
        "products",
        ["company_id", "spec_id", "print_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column("products", "print_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
