"""ad_products m2m, drop ad.product_id, order_items

Revision ID: a8c49317fdb9
Revises: 86d7531f48b7
Create Date: 2026-06-07 20:12:43.819110

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8c49317fdb9"
down_revision: str | Sequence[str] | None = "86d7531f48b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_products",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("ad_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["ad_id"], ["ads.id"], name=op.f("fk_ad_products_ad_id_ads"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_ad_products_company_id_companies")),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_ad_products_product_id_products"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_products")),
        sa.UniqueConstraint("ad_id", "product_id", name="uq_ad_products_ad_id_product_id"),
    )
    op.create_index(op.f("ix_ad_products_ad_id"), "ad_products", ["ad_id"], unique=False)
    op.create_index(op.f("ix_ad_products_company_id"), "ad_products", ["company_id"], unique=False)
    op.create_index(op.f("ix_ad_products_product_id"), "ad_products", ["product_id"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("variation_id", sa.Uuid(), nullable=True),
        sa.Column("tracking_code", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column(
            "status", postgresql.ENUM("pending", "label_printed", "checked", name="separation_status"), nullable=False
        ),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_by", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("mapped_print", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("item_index", sa.Integer(), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.CheckConstraint("item_index >= 0", name=op.f("ck_order_items_item_index_non_negative")),
        sa.CheckConstraint("total_items >= 0", name=op.f("ck_order_items_total_items_non_negative")),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], name=op.f("fk_order_items_company_id_companies")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_items_order_id_orders"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["variation_id"],
            ["product_variations.id"],
            name=op.f("fk_order_items_variation_id_product_variations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_company_id"), "order_items", ["company_id"], unique=False)
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_items_variation_id"), "order_items", ["variation_id"], unique=False)
    op.create_index(
        "uq_order_items_company_id_tracking_code",
        "order_items",
        ["company_id", "tracking_code"],
        unique=True,
        postgresql_where=sa.text("tracking_code IS NOT NULL"),
    )
    op.drop_index(op.f("ix_ads_product_id"), table_name="ads")
    op.drop_constraint(op.f("fk_ads_product_id_products"), "ads", type_="foreignkey")
    op.drop_column("ads", "product_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ads", sa.Column("product_id", sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(
        op.f("fk_ads_product_id_products"), "ads", "products", ["product_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_index(op.f("ix_ads_product_id"), "ads", ["product_id"], unique=False)
    op.drop_index(
        "uq_order_items_company_id_tracking_code",
        table_name="order_items",
        postgresql_where=sa.text("tracking_code IS NOT NULL"),
    )
    op.drop_index(op.f("ix_order_items_variation_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_company_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_ad_products_product_id"), table_name="ad_products")
    op.drop_index(op.f("ix_ad_products_company_id"), table_name="ad_products")
    op.drop_index(op.f("ix_ad_products_ad_id"), table_name="ad_products")
    op.drop_table("ad_products")
    postgresql.ENUM(name="separation_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
