"""add cutting run cost

Revision ID: bc63b4a72462
Revises: eb7a495ce346
Create Date: 2026-06-08 22:47:18.434409

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc63b4a72462"
down_revision: str | Sequence[str] | None = "eb7a495ce346"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cutting_run_costs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("cutting_order_id", sa.Uuid(), nullable=False),
        sa.Column("total_pieces", sa.Integer(), nullable=False),
        sa.Column("body_fabric_kg", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("ribana_kg", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("body_price_per_kg", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("rib_price_per_kg", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("fabric_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("ribana_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("trims_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("labor_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cost_per_piece", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("yield_pieces_per_kg", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.CheckConstraint("body_fabric_kg >= 0", name=op.f("ck_cutting_run_costs_body_fabric_kg_non_negative")),
        sa.CheckConstraint("cost_per_piece >= 0", name=op.f("ck_cutting_run_costs_cost_per_piece_non_negative")),
        sa.CheckConstraint("fabric_cost >= 0", name=op.f("ck_cutting_run_costs_fabric_cost_non_negative")),
        sa.CheckConstraint("labor_cost >= 0", name=op.f("ck_cutting_run_costs_labor_cost_non_negative")),
        sa.CheckConstraint("ribana_cost >= 0", name=op.f("ck_cutting_run_costs_ribana_cost_non_negative")),
        sa.CheckConstraint("ribana_kg >= 0", name=op.f("ck_cutting_run_costs_ribana_kg_non_negative")),
        sa.CheckConstraint("total_cost >= 0", name=op.f("ck_cutting_run_costs_total_cost_non_negative")),
        sa.CheckConstraint("total_pieces >= 0", name=op.f("ck_cutting_run_costs_total_pieces_non_negative")),
        sa.CheckConstraint("trims_cost >= 0", name=op.f("ck_cutting_run_costs_trims_cost_non_negative")),
        sa.CheckConstraint(
            "yield_pieces_per_kg >= 0", name=op.f("ck_cutting_run_costs_yield_pieces_per_kg_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_cutting_run_costs_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["cutting_order_id"],
            ["cutting_orders.id"],
            name=op.f("fk_cutting_run_costs_cutting_order_id_cutting_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cutting_run_costs")),
    )
    op.create_index(op.f("ix_cutting_run_costs_company_id"), "cutting_run_costs", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_cutting_run_costs_cutting_order_id"), "cutting_run_costs", ["cutting_order_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cutting_run_costs_cutting_order_id"), table_name="cutting_run_costs")
    op.drop_index(op.f("ix_cutting_run_costs_company_id"), table_name="cutting_run_costs")
    op.drop_table("cutting_run_costs")
    # ### end Alembic commands ###
