"""'add batches'

Revision ID: c57941a33511
Revises: 52d3c18cd680
Create Date: 2026-06-04 20:40:14.466699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c57941a33511'
down_revision: Union[str, Sequence[str], None] = '52d3c18cd680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('status', postgresql.ENUM('open', 'adjusted', 'printed', 'done', 'cancelled', name='batch_status'), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_pieces', sa.Integer(), nullable=False),
    sa.Column('labels_printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prints_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.CheckConstraint('total_orders >= 0', name=op.f('ck_batches_total_orders_non_negative')),
    sa.CheckConstraint('total_pieces >= 0', name=op.f('ck_batches_total_pieces_non_negative')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_batches_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches')),
    sa.UniqueConstraint('company_id', 'code', name='uq_batches_company_id_code')
    )
    op.create_index(op.f('ix_batches_company_id'), 'batches', ['company_id'], unique=False)
    op.create_table('batch_print_adjustments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('print_design_id', sa.Uuid(), nullable=False),
    sa.Column('product_color', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('qty_needed', sa.Integer(), nullable=False),
    sa.Column('qty_stock', sa.Integer(), nullable=False),
    sa.Column('qty_to_print', sa.Integer(), nullable=False),
    sa.Column('prints_sent', sa.Boolean(), nullable=False),
    sa.CheckConstraint('qty_needed >= 0', name=op.f('ck_batch_print_adjustments_qty_needed_non_negative')),
    sa.CheckConstraint('qty_stock >= 0', name=op.f('ck_batch_print_adjustments_qty_stock_non_negative')),
    sa.CheckConstraint('qty_to_print >= 0', name=op.f('ck_batch_print_adjustments_qty_to_print_non_negative')),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_batch_print_adjustments_batch_id_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_batch_print_adjustments_company_id_companies')),
    sa.ForeignKeyConstraint(['print_design_id'], ['print_designs.id'], name=op.f('fk_batch_print_adjustments_print_design_id_print_designs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_print_adjustments')),
    sa.UniqueConstraint('batch_id', 'print_design_id', 'product_color', name='uq_batch_print_adjustments_design_color')
    )
    op.create_index(op.f('ix_batch_print_adjustments_batch_id'), 'batch_print_adjustments', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_print_adjustments_company_id'), 'batch_print_adjustments', ['company_id'], unique=False)
    op.create_index(op.f('ix_batch_print_adjustments_print_design_id'), 'batch_print_adjustments', ['print_design_id'], unique=False)
    op.add_column('orders', sa.Column('batch_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_orders_batch_id'), 'orders', ['batch_id'], unique=False)
    op.create_foreign_key(op.f('fk_orders_batch_id_batches'), 'orders', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_orders_batch_id_batches'), 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_batch_id'), table_name='orders')
    op.drop_column('orders', 'batch_id')
    op.drop_index(op.f('ix_batch_print_adjustments_print_design_id'), table_name='batch_print_adjustments')
    op.drop_index(op.f('ix_batch_print_adjustments_company_id'), table_name='batch_print_adjustments')
    op.drop_index(op.f('ix_batch_print_adjustments_batch_id'), table_name='batch_print_adjustments')
    op.drop_table('batch_print_adjustments')
    op.drop_index(op.f('ix_batches_company_id'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
