"""add stock_committed_at to batch_print_adjustments

Revision ID: eb7a495ce346
Revises: 95e36cb45a49
Create Date: 2026-06-08 21:10:17.996165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb7a495ce346'
down_revision: Union[str, Sequence[str], None] = '95e36cb45a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_print_adjustments', sa.Column('stock_committed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch_print_adjustments', 'stock_committed_at')
    # ### end Alembic commands ###
