"""add low_stock_threshold to companies and product_variations

Revision ID: f6cb947bdbce
Revises: 50f7cf46097a
Create Date: 2026-06-09 00:03:01.754498

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6cb947bdbce"
down_revision: str | Sequence[str] | None = "50f7cf46097a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Company-wide threshold: NOT NULL with a server_default so existing rows
    # backfill to the default (10) — mirrors the montador_user_email precedent.
    op.add_column(
        "companies",
        sa.Column("low_stock_threshold", sa.Integer(), nullable=False, server_default="10"),
    )
    # Per-variation override is optional: NULL means "inherit the company default".
    op.add_column(
        "product_variations",
        sa.Column("low_stock_threshold", sa.Integer(), nullable=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_variations", "low_stock_threshold")
    op.drop_column("companies", "low_stock_threshold")
    # ### end Alembic commands ###
