"""'initial schema'

Revision ID: feea7ff730da
Revises: 
Create Date: 2026-05-06 20:52:13.249100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'feea7ff730da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('subdomain', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('main_color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.CheckConstraint("main_color ~ '^#[0-9A-Fa-f]{6}$'", name=op.f('ck_companies_main_color_hex')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_subdomain'), 'companies', ['subdomain'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_clients_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_index(op.f('ix_clients_company_id'), 'clients', ['company_id'], unique=False)
    op.create_table('fabric_rolls',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('received_at', sa.Date(), nullable=False),
    sa.Column('supplier_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('kind', postgresql.ENUM('body', 'rib', name='fabric_roll_kind'), nullable=False),
    sa.Column('fabric_type', postgresql.ENUM('jersey', 'fleece', 'french_terry', 'mesh', 'rib', name='fabric_type'), nullable=False),
    sa.Column('initial_weight_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('current_weight_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('current_weight_kg >= 0', name=op.f('ck_fabric_rolls_current_weight_non_negative')),
    sa.CheckConstraint('initial_weight_kg > 0', name=op.f('ck_fabric_rolls_initial_weight_positive')),
    sa.CheckConstraint('price_per_kg >= 0', name=op.f('ck_fabric_rolls_price_per_kg_non_negative')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_fabric_rolls_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fabric_rolls'))
    )
    op.create_index(op.f('ix_fabric_rolls_company_id'), 'fabric_rolls', ['company_id'], unique=False)
    op.create_table('print_designs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('cost_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_print_designs_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_print_designs')),
    sa.UniqueConstraint('company_id', 'code', name='uq_print_designs_company_id_code')
    )
    op.create_index(op.f('ix_print_designs_company_id'), 'print_designs', ['company_id'], unique=False)
    op.create_table('product_specs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('fabric_type', postgresql.ENUM('jersey', 'fleece', 'french_terry', 'mesh', 'rib', name='fabric_type'), nullable=False),
    sa.Column('fabric_grammage_gsm', sa.Integer(), nullable=False),
    sa.Column('fabric_weight_per_piece_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('has_ribana', sa.Boolean(), nullable=False),
    sa.Column('ribana_weight_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint('(has_ribana = false AND ribana_weight_pct IS NULL) OR (has_ribana = true AND ribana_weight_pct IS NOT NULL)', name=op.f('ck_product_specs_ribana_pct_iff_has_ribana')),
    sa.CheckConstraint('ribana_weight_pct IS NULL OR (ribana_weight_pct > 0 AND ribana_weight_pct <= 100)', name=op.f('ck_product_specs_ribana_weight_pct_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_product_specs_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_specs')),
    sa.UniqueConstraint('company_id', 'code', name='uq_product_specs_company_id_code')
    )
    op.create_index(op.f('ix_product_specs_company_id'), 'product_specs', ['company_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('sewing_contractors',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sewing_contractors_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sewing_contractors')),
    sa.UniqueConstraint('company_id', 'name', name='uq_sewing_contractors_company_id_name')
    )
    op.create_index(op.f('ix_sewing_contractors_company_id'), 'sewing_contractors', ['company_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('job', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('is_operator', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_users_company_id_companies')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('company_id', 'email', name='uq_users_company_id_email'),
    sa.UniqueConstraint('company_id', 'firebase_uid', name='uq_users_company_id_firebase_uid')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('product_type', postgresql.ENUM('tshirt', 'sweatshirt', 'shorts', 'tanktop', name='product_type'), nullable=False),
    sa.Column('spec_id', sa.Uuid(), nullable=False),
    sa.Column('print_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_products_company_id_companies')),
    sa.ForeignKeyConstraint(['print_id'], ['print_designs.id'], name=op.f('fk_products_print_id_print_designs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['spec_id'], ['product_specs.id'], name=op.f('fk_products_spec_id_product_specs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('company_id', 'spec_id', 'print_id', name='uq_products_spec_id_print_id')
    )
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index(op.f('ix_products_print_id'), 'products', ['print_id'], unique=False)
    op.create_index(op.f('ix_products_spec_id'), 'products', ['spec_id'], unique=False)
    op.create_table('spec_trims',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('spec_id', sa.Uuid(), nullable=False),
    sa.Column('trim_type', postgresql.ENUM('button', 'zipper', 'label', 'drawstring', 'snap', 'hook', 'eyelet', 'elastic', name='trim_type'), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spec_id'], ['product_specs.id'], name=op.f('fk_spec_trims_spec_id_product_specs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spec_trims'))
    )
    op.create_index(op.f('ix_spec_trims_spec_id'), 'spec_trims', ['spec_id'], unique=False)
    op.create_table('ads',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('ecommerce', postgresql.ENUM('shopee', 'mercado_livre', 'shopify', 'instagram', 'whatsapp', 'other', name='ecommerce'), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ads_company_id_companies')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_ads_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ads'))
    )
    op.create_index(op.f('ix_ads_company_id'), 'ads', ['company_id'], unique=False)
    op.create_index(op.f('ix_ads_product_id'), 'ads', ['product_id'], unique=False)
    op.create_table('cutting_orders',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('body_roll_id', sa.Uuid(), nullable=False),
    sa.Column('rib_roll_id', sa.Uuid(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'cutting', 'done', name='cutting_status'), nullable=False),
    sa.Column('cut_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('body_roll_id <> rib_roll_id', name=op.f('ck_cutting_orders_body_and_rib_rolls_differ')),
    sa.ForeignKeyConstraint(['body_roll_id'], ['fabric_rolls.id'], name=op.f('fk_cutting_orders_body_roll_id_fabric_rolls'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_cutting_orders_company_id_companies')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_cutting_orders_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rib_roll_id'], ['fabric_rolls.id'], name=op.f('fk_cutting_orders_rib_roll_id_fabric_rolls'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cutting_orders'))
    )
    op.create_index(op.f('ix_cutting_orders_body_roll_id'), 'cutting_orders', ['body_roll_id'], unique=False)
    op.create_index(op.f('ix_cutting_orders_company_id'), 'cutting_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_cutting_orders_product_id'), 'cutting_orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_cutting_orders_rib_roll_id'), 'cutting_orders', ['rib_roll_id'], unique=False)
    op.create_table('product_variations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('size', postgresql.ENUM('p', 'm', 'g', 'gg', name='size'), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('color_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.CheckConstraint("color_code ~ '^[A-Z]{3}$'", name=op.f('ck_product_variations_color_code_format')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_product_variations_company_id_companies')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variations_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variations')),
    sa.UniqueConstraint('company_id', 'product_id', 'size', 'color_code', name='uq_product_variations_product_id_size_color_code'),
    sa.UniqueConstraint('company_id', 'sku', name='uq_product_variations_company_id_sku')
    )
    op.create_index(op.f('ix_product_variations_company_id'), 'product_variations', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_variations_product_id'), 'product_variations', ['product_id'], unique=False)
    op.create_table('cutting_order_outputs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cutting_order_id', sa.Uuid(), nullable=False),
    sa.Column('size', postgresql.ENUM('p', 'm', 'g', 'gg', name='size'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_cutting_order_outputs_quantity_non_negative')),
    sa.ForeignKeyConstraint(['cutting_order_id'], ['cutting_orders.id'], name=op.f('fk_cutting_order_outputs_cutting_order_id_cutting_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cutting_order_outputs')),
    sa.UniqueConstraint('cutting_order_id', 'size', name='uq_cutting_order_outputs_cutting_order_id_size')
    )
    op.create_index(op.f('ix_cutting_order_outputs_cutting_order_id'), 'cutting_order_outputs', ['cutting_order_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('ad_id', sa.Uuid(), nullable=False),
    sa.Column('variation_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'shipped', 'delivered', 'cancelled', 'returned', name='order_status'), nullable=False),
    sa.Column('external_order_id', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_orders_quantity_positive')),
    sa.CheckConstraint('sale_price >= 0', name=op.f('ck_orders_sale_price_non_negative')),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name=op.f('fk_orders_ad_id_ads'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_orders_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_orders_company_id_companies')),
    sa.ForeignKeyConstraint(['variation_id'], ['product_variations.id'], name=op.f('fk_orders_variation_id_product_variations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_ad_id'), 'orders', ['ad_id'], unique=False)
    op.create_index(op.f('ix_orders_client_id'), 'orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_orders_company_id'), 'orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_orders_variation_id'), 'orders', ['variation_id'], unique=False)
    op.create_index('uq_orders_company_id_ad_id_external_order_id', 'orders', ['company_id', 'ad_id', 'external_order_id'], unique=True, postgresql_where=sa.text('external_order_id IS NOT NULL'))
    op.create_table('sewing_shipments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('cutting_order_id', sa.Uuid(), nullable=False),
    sa.Column('contractor_id', sa.Uuid(), nullable=False),
    sa.Column('sent_at', sa.Date(), nullable=False),
    sa.Column('received_at', sa.Date(), nullable=True),
    sa.Column('status', postgresql.ENUM('sent', 'received', 'partial', 'cancelled', name='shipment_status'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sewing_shipments_company_id_companies')),
    sa.ForeignKeyConstraint(['contractor_id'], ['sewing_contractors.id'], name=op.f('fk_sewing_shipments_contractor_id_sewing_contractors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cutting_order_id'], ['cutting_orders.id'], name=op.f('fk_sewing_shipments_cutting_order_id_cutting_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sewing_shipments'))
    )
    op.create_index(op.f('ix_sewing_shipments_company_id'), 'sewing_shipments', ['company_id'], unique=False)
    op.create_index(op.f('ix_sewing_shipments_contractor_id'), 'sewing_shipments', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_sewing_shipments_cutting_order_id'), 'sewing_shipments', ['cutting_order_id'], unique=False)
    op.create_table('sewing_shipment_items',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('size', postgresql.ENUM('p', 'm', 'g', 'gg', name='size'), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('received_quantity <= requested_quantity', name=op.f('ck_sewing_shipment_items_received_within_requested')),
    sa.CheckConstraint('received_quantity >= 0', name=op.f('ck_sewing_shipment_items_received_non_negative')),
    sa.CheckConstraint('requested_quantity >= 0', name=op.f('ck_sewing_shipment_items_requested_non_negative')),
    sa.ForeignKeyConstraint(['shipment_id'], ['sewing_shipments.id'], name=op.f('fk_sewing_shipment_items_shipment_id_sewing_shipments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sewing_shipment_items')),
    sa.UniqueConstraint('shipment_id', 'size', name='uq_sewing_shipment_items_shipment_id_size')
    )
    op.create_index(op.f('ix_sewing_shipment_items_shipment_id'), 'sewing_shipment_items', ['shipment_id'], unique=False)
    op.create_table('stock_entries',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('variation_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('source', postgresql.ENUM('shipment', 'adjustment', 'return', name='stock_source'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_stock_entries_quantity_positive')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_entries_company_id_companies')),
    sa.ForeignKeyConstraint(['shipment_id'], ['sewing_shipments.id'], name=op.f('fk_stock_entries_shipment_id_sewing_shipments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variation_id'], ['product_variations.id'], name=op.f('fk_stock_entries_variation_id_product_variations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_entries'))
    )
    op.create_index(op.f('ix_stock_entries_company_id'), 'stock_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_entries_shipment_id'), 'stock_entries', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_stock_entries_variation_id'), 'stock_entries', ['variation_id'], unique=False)
    op.create_table('stock_exits',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('variation_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', postgresql.ENUM('sale', 'adjustment', 'loss', name='stock_exit_reason'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_stock_exits_quantity_positive')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_exits_company_id_companies')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_stock_exits_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variation_id'], ['product_variations.id'], name=op.f('fk_stock_exits_variation_id_product_variations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_exits'))
    )
    op.create_index(op.f('ix_stock_exits_company_id'), 'stock_exits', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_exits_order_id'), 'stock_exits', ['order_id'], unique=False)
    op.create_index(op.f('ix_stock_exits_variation_id'), 'stock_exits', ['variation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_exits_variation_id'), table_name='stock_exits')
    op.drop_index(op.f('ix_stock_exits_order_id'), table_name='stock_exits')
    op.drop_index(op.f('ix_stock_exits_company_id'), table_name='stock_exits')
    op.drop_table('stock_exits')
    op.drop_index(op.f('ix_stock_entries_variation_id'), table_name='stock_entries')
    op.drop_index(op.f('ix_stock_entries_shipment_id'), table_name='stock_entries')
    op.drop_index(op.f('ix_stock_entries_company_id'), table_name='stock_entries')
    op.drop_table('stock_entries')
    op.drop_index(op.f('ix_sewing_shipment_items_shipment_id'), table_name='sewing_shipment_items')
    op.drop_table('sewing_shipment_items')
    op.drop_index(op.f('ix_sewing_shipments_cutting_order_id'), table_name='sewing_shipments')
    op.drop_index(op.f('ix_sewing_shipments_contractor_id'), table_name='sewing_shipments')
    op.drop_index(op.f('ix_sewing_shipments_company_id'), table_name='sewing_shipments')
    op.drop_table('sewing_shipments')
    op.drop_index('uq_orders_company_id_ad_id_external_order_id', table_name='orders', postgresql_where=sa.text('external_order_id IS NOT NULL'))
    op.drop_index(op.f('ix_orders_variation_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_company_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_ad_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_cutting_order_outputs_cutting_order_id'), table_name='cutting_order_outputs')
    op.drop_table('cutting_order_outputs')
    op.drop_index(op.f('ix_product_variations_product_id'), table_name='product_variations')
    op.drop_index(op.f('ix_product_variations_company_id'), table_name='product_variations')
    op.drop_table('product_variations')
    op.drop_index(op.f('ix_cutting_orders_rib_roll_id'), table_name='cutting_orders')
    op.drop_index(op.f('ix_cutting_orders_product_id'), table_name='cutting_orders')
    op.drop_index(op.f('ix_cutting_orders_company_id'), table_name='cutting_orders')
    op.drop_index(op.f('ix_cutting_orders_body_roll_id'), table_name='cutting_orders')
    op.drop_table('cutting_orders')
    op.drop_index(op.f('ix_ads_product_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_company_id'), table_name='ads')
    op.drop_table('ads')
    op.drop_index(op.f('ix_spec_trims_spec_id'), table_name='spec_trims')
    op.drop_table('spec_trims')
    op.drop_index(op.f('ix_products_spec_id'), table_name='products')
    op.drop_index(op.f('ix_products_print_id'), table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sewing_contractors_company_id'), table_name='sewing_contractors')
    op.drop_table('sewing_contractors')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_product_specs_company_id'), table_name='product_specs')
    op.drop_table('product_specs')
    op.drop_index(op.f('ix_print_designs_company_id'), table_name='print_designs')
    op.drop_table('print_designs')
    op.drop_index(op.f('ix_fabric_rolls_company_id'), table_name='fabric_rolls')
    op.drop_table('fabric_rolls')
    op.drop_index(op.f('ix_clients_company_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_companies_subdomain'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
